I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 37, in script
    show text "{glitch 5.0}{color=#0aad07}4 months earlier...{/glitch}{/color}"
  File "game/script.rpy", line 37, in script
    show text "{glitch 5.0}{color=#0aad07}4 months earlier...{/glitch}{/color}"
AttributeError: 'str' object has no attribute 'get'

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "C:\Users\Sylviane\Desktop\renpy-8.1.3-sdk\renpy\bootstrap.py", line 275, in bootstrap
    renpy.main.main()
  File "C:\Users\Sylviane\Desktop\renpy-8.1.3-sdk\renpy\main.py", line 670, in main
    run(restart)
  File "C:\Users\Sylviane\Desktop\renpy-8.1.3-sdk\renpy\main.py", line 144, in run
    renpy.execution.run_context(True)
  File "C:\Users\Sylviane\Desktop\renpy-8.1.3-sdk\renpy\execution.py", line 955, in run_context
    context.run()
  File "game/script.rpy", line 37, in script
    show text "{glitch 5.0}{color=#0aad07}4 months earlier...{/glitch}{/color}"
  File "/home/tom/ab/renpy-build-fix/tmp/install.linux-x86_64/lib/python3.9/site-packages/future/utils/__init__.py", line 444, in raise_
  File "game/script.rpy", line 37, in script
    show text "{glitch 5.0}{color=#0aad07}4 months earlier...{/glitch}{/color}"
  File "C:\Users\Sylviane\Desktop\renpy-8.1.3-sdk\renpy\ast.py", line 1428, in execute
    show_imspec(self.imspec, atl=getattr(self, "atl", None))
  File "C:\Users\Sylviane\Desktop\renpy-8.1.3-sdk\renpy\ast.py", line 1391, in show_imspec
    renpy.config.show(name,
  File "C:\Users\Sylviane\Desktop\renpy-8.1.3-sdk\renpy\exports.py", line 759, in show
    sls.add(layer, img, key, zorder, behind, at_list=at_list, name=name, atl=atl, default_transform=default_transform, transient=transient)
  File "C:\Users\Sylviane\Desktop\renpy-8.1.3-sdk\renpy\display\core.py", line 1280, in add
    thing.visit_all(lambda d : None)
  File "C:\Users\Sylviane\Desktop\renpy-8.1.3-sdk\renpy\display\core.py", line 684, in visit_all
    d.visit_all(callback, seen)
  File "C:\Users\Sylviane\Desktop\renpy-8.1.3-sdk\renpy\display\core.py", line 684, in visit_all
    d.visit_all(callback, seen)
  File "C:\Users\Sylviane\Desktop\renpy-8.1.3-sdk\renpy\display\core.py", line 674, in visit_all
    for d in self.visit():
  File "C:\Users\Sylviane\Desktop\renpy-8.1.3-sdk\renpy\text\text.py", line 1891, in visit
    self.update()
  File "C:\Users\Sylviane\Desktop\renpy-8.1.3-sdk\renpy\text\text.py", line 1868, in update
    tokens = self.apply_custom_tags(tokens)
  File "C:\Users\Sylviane\Desktop\renpy-8.1.3-sdk\renpy\text\text.py", line 2381, in apply_custom_tags
    func = renpy.config.custom_text_tags.get(tag, None)
AttributeError: 'str' object has no attribute 'get'

Windows-10-10.0.14393 AMD64
Ren'Py 8.1.3.23091805
Behind the Red Line _test_ 1.0
Tue Dec 19 22:06:57 2023
